language: scala
sudo: required
dist: trusty

matrix:
  include:
    # Scala 2.11
    - jdk: oraclejdk8
      scala: 2.11.11
      env: COMMAND=ci-jvm COVERAGE=coverage PUBLISH=
    - jdk: oraclejdk8
      scala: 2.11.11
      env: COMMAND=ci-js COVERAGE= PUBLISH=
    # Scala 2.12
    - jdk: oraclejdk8
      scala: 2.12.2
      env: COMMAND=ci-jvm-all COVERAGE= PUBLISH=true
    - jdk: oraclejdk8
      scala: 2.12.2
      env: COMMAND=ci-js PUBLISH= COVERAGE=

env:
  global:
    - TRAVIS_NODE_VERSION="6.10" # LTS

before_install:
  - openssl aes-256-cbc -K $encrypted_4413938994d3_key -iv $encrypted_4413938994d3_iv -in project/.gnupg/pubring.gpg.enc -out project/.gnupg/pubring.gpg -d
  - openssl aes-256-cbc -K $encrypted_4257a4a5aee2_key -iv $encrypted_4257a4a5aee2_iv -in project/.gnupg/secring.gpg.enc -out project/.gnupg/secring.gpg -d

# http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - export SBT_PROFILE=$COVERAGE
  - travis_wait 30 sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COVERAGE $COMMAND

after_success:
  - ./project/upload-coverage
  - ./project/publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
